name: "download-release-files-action"

description: "GitHub Action able to download release files. Search is limited to most recent 100 releases."
inputs:
  token:
    description: "GitHub Token. By default uses context token."
    default: ${{ github.token }}
    required: false
  repository:
    description: "Target release repository. By default uses current repository. Format {owner}/{repositoryName}"
    default: ${{ github.repository }}
    required: false
  release_name:
    description: "Target release name. Can use regex to match name. If not provided, the action will download latest available release."
    required: false
  file_name:
    description: "File(s) to be downloaded. If not provided, the action will download all available release files. Can use Regex to get multiple files eg. /(file1.exe|file2.exe)/ or /(.exe|.zip)/"
    required: false
    default: /./

runs:
  using: "node16"
  main: "main.js"
