name: "download-release-files-action"

description: "GitHub Action able to download release files"
inputs:
  token:
    description: "GitHub Token. By default uses context token"
    default: ${{ github.token }}
    required: false
  repository:
    description: "Target release repository. By default uses current repository. Format {owner}/{repositoryName}"
    default: ${{ github.repository }}
    required: false

runs:
  using: "node12"
  main: "main.js"
